allowBuilds:
  esbuild: true
  vue-demi: true
minimumReleaseAgeExclude:
  - brace-expansion@5.0.6
  - ws@8.20.1
  - js-cookie@3.0.6
  - esbuild@0.28.1
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - vue-demi
