services: 
  backend-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3666:3666"
    restart: unless-stopped
    container_name: sudoku_backend
    volumes:
      - vue_sudoku_db:/data

  frontend-spa:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    restart: unless-stopped
    depends_on:
      - backend-api
    container_name: sudoku_frontend

volumes:
  vue_sudoku_db: 
    driver: local
